### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/imagewebp#2]
Some issues with the readme as committed:

* The instructions for use are still the default set from the example file. 
* Image module in the requirements, should be unlinked, and some text should be added indicating that this is a core module.
* The readme file still has `foo-project` where it should have `imagewebp`. 
* Names in the maintainers and credits section are example names, and need to be updated.

**Comment by jenlampton** [comment]
for the instructions section, this is what Ive been doing:

Image display settings:

1) Visit the display settings page for any entity with an image field (for example admin/structure/types/manage/ranking/display)
2) Configure the formatter settings
3) Check the box for ` Webp support `
4) (optionally) Also check the box for `Create webp images for all images of this field`

**Comment by larsdesigns** [comment]
@jenlampton, Do you want to be a maintainer?

**Comment by jenlampton** [comment]
Sure!

**Comment by larsdesigns** [comment]
Added @jenlampton as a maintainer for the project and listed her in the README.txt file for the current release.

**Comment by larsdesigns** [comment]
Updated the the README.md file as specified.

**Comment by larsdesigns** [comment]
@jenlampton, Let me know if it looks okay and we can close the ticket.

**Comment by jenlampton** [comment]
* In the requirements section, the Image module shouldn't be linked (since it is a core module) and there should be some indication in the text that it's a core module. Also, we should check and see if it's a required core module (can it be turned off?) and if so, remove this item entirely.
* There's a blockquote in the installation section (probably not intentional)
* "Current Maintainers" section title should be a heading like the others

**Comment by larsdesigns** [comment]
Updated the README.txt.

**Comment by jenlampton** [comment]
looks great!
