### ISSUE TITLE
Delete old master branch

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/imagewebp#4]
We need to get rid of the master branch. Since the current Drupal module version is 1.x and the Backdrop core version is 1.x, I'd like to recommend that we name the default branch for this module `1.x-1.x`.

**Comment by jenlampton** [comment]
I've added a `1.x-1.x` branch and switched this project's Default branch to it, but I'm leaving the master branch there until we're sure all contributors have switched over to the new default.

**Comment by larsdesigns** [comment]
1. Checked to make sure the 1.x-1.x is up to date. 
2. Deleted the master branch. 

No further tasks. Closing...
